import {
    END,
    START,
    StateGraph,
    StateSchema,
    type GraphNode,
} from '@langchain/langgraph';
import z, { promise } from 'zod';
import { cohereModel, geminiModel, mistralModel } from './model.ai.js';
import { createAgent, HumanMessage, providerStrategy } from 'langchain';

const state = new StateSchema({
    problem: z.string().default(''),
    solution_1: z.string().default(''),
    solution_2: z.string().default(''),
    judge: z.object({
        solution_1_score: z.number().min(0).max(0).default(0),
        solution_2_score: z.number().min(0).max(0).default(0),
        solution_1_reasoning: z.string().default(''),
        solution_2_reasoning: z.string().default(''),
    }),
});

const solutionNode: GraphNode<typeof state> = async (state) => {
    const [mistralResponse, cohereResponse] = await Promise.all([
        mistralModel.invoke(state.problem),
        cohereModel.invoke(state.problem),
    ]);

    return {
        solution_1: mistralResponse.text,
        solution_2: cohereResponse.text,
    };
};

const judgeNode: GraphNode<typeof state> = async (state) => {
    const { problem, solution_1, solution_2 } = state;

    const judge = createAgent({
        model: geminiModel,
        responseFormat: providerStrategy(
            z.object({
                solution_1_score: z.number().min(0).max(10),
                solution_2_score: z.number().min(0).max(10),
                solution_1_reasoning: z.string().default(''),
                solution_2_reasoning: z.string().default(''),
            }),
        ),
        systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models.Please Provide a each solution on a scale of 0 to 10, where 0 means the solution does not address the problem at all, and 10 means the solution fully addresses the problem. Provide your reasoning for each score.`,
    });

    const judgeResponse = await judge.invoke({
        messages: [
            new HumanMessage(`
                Problem: ${problem}
                Solution 1: ${solution_1}
                Solution 2: ${solution_2}
                Please evaluate the two solutions and provide scores and reasoning for each solution.
                `),
        ],
    });

    const {
        solution_1_score,
        solution_2_score,
        solution_1_reasoning,
        solution_2_reasoning,
    } = judgeResponse.structuredResponse;

    return {
        judge: {
            solution_1_score,
            solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning,
        },
    };
};

const graph = new StateGraph(state)
    .addNode('solution_node', solutionNode)
    .addNode('judge_node', judgeNode)
    .addEdge(START, 'solution_node')
    .addEdge('solution_node', 'judge_node')
    .addEdge('judge_node', END)
    .compile();

export default async function useGraph(problem: string) {
    const result = await graph.invoke({
        problem: problem,
    });

    return result;
}
